before_install: cd pw
language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $2bdbf8cddc48551ee47d728c899c377832cc7c45
 local_dir: dist
 on:
   branch: master